name: health check

on:
  push:
    branches:
      master
  schedule:
    - cron:  '59 23 * * *'

jobs:
  ping4health:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: https://pokedexfsodiego.herokuapp.com/health
        follow-redirect: false
        max-attempts: 3
        retry-delay: 10s
        retry-all: no